### ISSUE TITLE
vmware_tag_manager module error or failed to import the required Python library (vSphere Automation SDK) 

### ISSUE THREAD

**Issue by snsiregar** [vmware/vsphere-automation-sdk-python#250]
## Environment
- sdk package version: 
nsx-vmc-aws-integration-python-sdk 3.0.2.0.0.16837625
nsx-vmc-policy-python-sdk          3.0.2.0.0.16837625
pyvmomi                            7.0.1
vapi-client-bindings               3.5.0
vapi-common-client                 2.19.0
vapi-runtime                       2.19.0
vmc-client-bindings                1.30.0
vmc-draas-client-bindings          1.15.0
vSphere-Automation-SDK             1.42.0

- python version:
Python 2.7.5
Python 3.6.8

- vSphere version:
vSphere 6.5

- Operating System/Shell (used to run SDK-based apps):
Red Hat Enterprise Linux Server release 7.6 (Maipo)

## Steps or code snippet to reproduce
run this yaml file for python3
```yaml
vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Add tags to a virtual machine
    vmware_tag_manager:
      hostname: "{{  VMWARE_HOST }}"
      username: "{{  VMWARE_USER }}"
      password: "{{  VMWARE_PASSWORD }}"
      validate_certs: no
      tag_names:
        - RHELServer
      object_name: DEVRHEL
      object_type: VirtualMachine
      state: add
```
job log here:
{
    "exception": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1605859409.33-134568295864586/AnsiballZ_vmware_tag_manager.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1605859409.33-134568295864586/AnsiballZ_vmware_tag_manager.py\", line 17, in _ansiballz_main\n    import base64\n  File \"/usr/lib64/python3.6/base64.py\", line 9, in <module>\n    import re\n  File \"/usr/lib64/python3.6/re.py\", line 142, in <module>\n    class RegexFlag(enum.IntFlag):\nAttributeError: module 'enum' has no attribute 'IntFlag'\n",
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {
        "ansible_host": "localhost"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1605859409.33-134568295864586/AnsiballZ_vmware_tag_manager.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1605859409.33-134568295864586/AnsiballZ_vmware_tag_manager.py\", line 17, in _ansiballz_main\n    import base64\n  File \"/usr/lib64/python3.6/base64.py\", line 9, in <module>\n    import re\n  File \"/usr/lib64/python3.6/re.py\", line 142, in <module>\n    class RegexFlag(enum.IntFlag):\nAttributeError: module 'enum' has no attribute 'IntFlag'\n",
    "changed": false,
    "module_stdout": "",
    "rc": 1,
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}

run this yaml file for python2
```yaml
  tasks:
  - name: Add tags to a virtual machine
    vmware_tag_manager:
      hostname: "{{  VMWARE_HOST }}"
      username: "{{  VMWARE_USER }}"
      password: "{{  VMWARE_PASSWORD }}"
      validate_certs: no
      tag_names:
        - RHELServer
      object_name: DEVRHEL
      object_type: VirtualMachine
      state: add
```
job log here:
{
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_vmware_tag_manager_payload_veOEcW/ansible_vmware_tag_manager_payload.zip/ansible/module_utils/vmware_rest_client.py\", line 30, in <module>\n    from com.vmware.vapi.std_client import DynamicID\nImportError: No module named com.vmware.vapi.std_client\n",
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {
        "ansible_host": "localhost"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "username": "admin",
            "object_type": "VirtualMachine",
            "protocol": "https",
            "hostname": "10.10.10.10",
            "object_name": "DEVRHEL",
            "state": "add",
            "tag_names": [
                "RHELServer"
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": false
        }
    },
    "msg": "Failed to import the required Python library (vSphere Automation SDK) on MASTER03's Python /usr/bin/python2. See https://code.vmware.com/web/sdk/65/vsphere-automation-python for more info. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}

## Expected behavior
can't using vmware_tag_manager module on yaml file, when run others vmware module (tried snapshot and guest) is okay.
